language: go

go:
  - "1.11"

notifications:
  email: false

git:
  depth: 1

os: linux

script:
  - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
  - go test -v ./...

before_install:
  - go get golang.org/x/tools/cmd/goimports
